require 'aspire/object/digitisation'
require 'aspire/object/factory'
require 'aspire/object/list'
require 'aspire/object/module'
require 'aspire/object/resource'
require 'aspire/object/time_period'
require 'aspire/object/user'